### ISSUE TITLE
Override section config for specific field value

### ISSUE THREAD

**Issue by Kraymer** [Kraymer/flinck#27]
An example is that for movies of kind 'TV series' : you may want to store them at another place than others movies.

```
genre:
    dirs: true
    buckets: true
    link_format: %rating-%year-%title

genre=TV series:
    root: TV/
    buckets: true
    link_format:  %rating-%season-%year-%title
```

Config should be herited from parent section except for redefined fields
